### ISSUE TITLE
Suggestion: You can also simplify the CSS for the font-weight property.

### ISSUE THREAD

**Issue by josephtkim** [Klaphat/prj-rev-bwfs-dasmoto#4]
Great job simplifying the CSS code for several of the shared properties for the selectors. You can also simplify it further for the font-weight property, which has the same value for several selectors. You can do so like

```css
.headline, h2, .highlight {
  font-weight: bold;
}
```
